### ISSUE TITLE
Images inside post content

### ISSUE THREAD

**Issue by chmac** [GatsbyCentral/gatsby-starter-wordpress#22]
Currently the images inside the post content point to the WordPress domain. It would be nice to find a way to import them and load them via `<Image` if that's possible...

**Comment by LittleHamster** [comment]
@chmac any updates on this?

**Comment by chmac** [comment]
@LittleHamster Unfortunately not, I'm not even sure how to approach it. Not sure how `<Image` integrates with HTML from an external source. PRs welcome. :-)

**Comment by LittleHamster** [comment]
@chmac 
I created this issue https://github.com/gatsbyjs/gatsby/issues/11179 for reference

**Comment by chmac** [comment]
@LittleHamster Great, thanks. I'll close this issue now as I guess tackling this is beyond the scope of this starter. 👍
