### ISSUE TITLE
?_embed

### ISSUE THREAD

**Issue by elpuas** [GatsbyCentral/gatsby-starter-wordpress#33]
Should post support `?_embed` attr on  `${typePrefix}posts` ( `${typePrefix}posts?_embed`) ? 
It will be awesome to be able to added to <Images /> the feature image data. Possible? Feature?

**Comment by chmac** [comment]
@elpuas I don’t understand your question. Can you explain in more detail what you mean?

**Comment by elpuas** [comment]
Sorry to  not explain me well, what i'm trying to achieve is get the feature in the old version of the REST API, you can't get the feature image endpoint, so to achieve this you need to add ```?_embed``` to the endpoint to get the feature image data. so the new full endpoint for post will be:  ```/wp-json/wp/v2/posts?_embed``` make sense now? I believe this can be an upgrade to the plugin? make sense now

**Comment by chmac** [comment]
@elpuas Have you checked out the Gatsby GraphQL explorer? It shows you exactly what data comes from WordPress and is available to you. You can also check out the [wordpress source plugin](
https://www.gatsbyjs.org/packages/gatsby-source-wordpress/), that’s what actually pulls in data from WordPress. This starter is an example of how you can use the source plugin and display that data.

If I’ve understood your question correctly, it’s not related to this starter, so I’ll close this issue now. If you think I’ve misunderstood, feel free to reply and / or reopen the issue.

**Comment by elpuas** [comment]
Yes you will right, I see that the feature image is showing in GraphQL data. Thanks!
