### ISSUE TITLE
Permalink structure for posts?

### ISSUE THREAD

**Issue by LittleHamster** [GatsbyCentral/gatsby-starter-wordpress#38]
Is it possible to change the post permalink structure?
in WP I have set it to : 
```
/%year%/%monthnum%/%day%/%postname%/
```

so the output would be 
```
/2019/01/20/sample-post/
```

how can I get the similar custom links?

**Comment by chmac** [comment]
You could customise the page link logic here:

https://github.com/GatsbyCentral/gatsby-starter-wordpress/blob/2f5ede59ec1dad6ae228b86378f79d031b305f34/gatsby-node.js#L45-L51
