### ISSUE TITLE
Add `develop: true` to purgecss config

### ISSUE THREAD

**Issue by bjfresh** [GatsbyCentral/gatsby-starter-wordpress#40]
I was having an issue (see https://github.com/gatsbyjs/gatsby/issues/12226) where style output was different in production than in development, and tracked it back to purgecss eliminating live styles. I'd recommend configuring purgecss as active in developer mode (and possibly also adding terminal output for purged selectors) using the following configuration. I'd imagine this to be an issue that would catch a lot of developers by surprise.

```javascript
    {
      resolve: 'gatsby-plugin-purgecss', // purges all unused/unreferenced css rules
      options: {
        develop: true,            // Activates purging in npm run develop
        printRejected: true  // Show purged CSS selectors in terminal output
      },
    },
```

**Comment by chmac** [comment]
@bjfresh Sorry you hit this problem. We knew it was a risk when we added `purgecss`. Your suggestion about adding `develop: true` makes a lot of sense. I'll add that.

**Comment by anantoghosh** [comment]
@chmac I would mention, with `gatsby-plugin-purgecss` v3.1.0 you could add  `purgeOnly: ['/all.sass']` option, similar to how the [netlify starter does now](https://github.com/netlify-templates/gatsby-starter-netlify-cms/blob/fd19cad76da7b08e9b4f1911e0b16afea1c332cb/gatsby-config.js#L69), to make sure only your specified style get purged.

**Comment by chmac** [comment]
@anantoghosh Great, thanks. That sounds like a nice tip.

If either @bjfresh or @anantoghosh are up for submitting a PR, that would be awesome.

We originally submitted the [PR](https://github.com/netlify-templates/gatsby-starter-netlify-cms/pull/125) adding `purgecss` to netlify, glad to see it's taken off. :-)
