### ISSUE TITLE
Updating gatsby package to latest (2.18.1) breaks gatsby develop

### ISSUE THREAD

**Issue by jeffreznik** [GatsbyCentral/gatsby-starter-wordpress#47]
## Description

As the title says, if you pull this starter and upgrade the `gatsby` package to the latest version, currently `2.18.1`, running `gatsby develop` will throw errors and break.  Current version in this `package.json` is `2.15.14`

### Steps to reproduce

1. Pull this starter: `npx gatsby new gatsby-starter-wordpress https://github.com/GatsbyCentral/gatsby-starter-wordpress`
2. `cd gatsby-starter-wordpress`
3. `npx gatsby develop`
4. Everything works fine, shut down dev server.
5. `npm install gatsby@latest`
6. `npx gatsby develop`
7. Errors thrown and breaks.

### Expected result

Dev server should start fine as before package update.

### Actual result

Here is the error output:
```
The above error occurred in the <StoreStateProvider> component:
    in StoreStateProvider
    in App

React will try to recreate this component tree from scratch using the error boundary you provided, App.
Warning: App: Error boundaries should implement getDerivedStateFromError(). In that method, return a state update to display an error message or fallback UI.
```
### Environment

  System:
    OS: macOS Mojave 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-4750HQ CPU @ 2.00GHz
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Languages:
    Python: 2.7.10 - /usr/bin/python
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 37.0.2
    Safari: 13.0.2

**Comment by jeffreznik** [comment]
Figured it out after searching some more, a delete of `node_modules` **and** `package-lock.json` and fresh `npm install` fixes the issue.

Ref: https://github.com/gatsbyjs/gatsby/issues/19064#issuecomment-547525103

**Comment by chmac** [comment]
@jeffreznik Thanks for the issue, and especially for closing it. :-)

If you figured out what is required to fix this, we'd be happy to merge a PR that upgrades to the latest version and fixes the `package-lock.json` issue. That might save other folks similar headaches.

**Comment by jeffreznik** [comment]
Done! PR: #48
