### ISSUE TITLE
Won't generate pages from WordPress.com-hosted site

### ISSUE THREAD

**Issue by markedup** [GatsbyCentral/gatsby-starter-wordpress#5]
I can't seem to get this to crawl a site I have hosted with WordPress.com successfully. The relevant part of my Gatsby config is as follows:

      options: {
        baseUrl: WP_URL, // e.g. "demo1234.wordpress.com"
        hostingWPCOM: true,
        protocol: "http",
        useACF: false,
        auth: {
          wpcom_app_clientId: WP_CLIENT_ID,
          wpcom_app_clientSecret: WP_CLIENT_SECRET
          wpcom_user: WP_USER_EMAIL,
          wpcom_pass: WP_USER_PASSWORD
        },
        verboseOutput: true
      }

From the verbose output, I get the following error:

    =START PLUGIN=====================================

    Site URL: http://demo1234.wordpress.com
    Site hosted on Wordpress.com: true
    Using ACF: false
    Using Auth: undefined undefined
    Verbose output: true

    Mama Route URL: https://public-api.wordpress.com/wp/v2/sites/demo1234.wordpress.com

I then get a raft of "Invalid route" notifications, amongst a few valid ones—it seems to relate to any param-based URLs:

    ⡀ source and transform nodesRoute discovered : /wp/v2
    Invalid route.
    Route discovered : /wp/v2/sites/demo1234.wordpress.com
    Invalid route.
    Route discovered : /wp/v2/sites/demo1234.wordpress.com/posts/(?P<parent>[\d]+)/autosaves
    Invalid route.
    Route discovered : /wp/v2/sites/demo1234.wordpress.com/posts/(?P<parent>[\d]+)/autosaves/(?P<id>[\d]+)
    Invalid route.
    Route discovered : /wp/v2/sites/demo1234.wordpress.com/pages/(?P<parent>[\d]+)/autosaves
    Invalid route.
    Route discovered : /wp/v2/sites/demo1234.wordpress.com/pages/(?P<parent>[\d]+)/autosaves/(?P<id>[\d]+)
    Invalid route.
    Route discovered : /wp/v2/sites/demo1234.wordpress.com/posts
    Valid route found. Will try to fetch.
    Route discovered : /wp/v2/sites/demo1234.wordpress.com/posts/(?P<id>[\d]+)
    Invalid route.
    Route discovered : /wp/v2/sites/demo1234.wordpress.com/posts/(?P<parent>[\d]+)/revisions
    Invalid route.
    Route discovered : /wp/v2/sites/demo1234.wordpress.com/posts/(?P<parent>[\d]+)/revisions/(?P<id>[\d]+)
    Invalid route.
    Route discovered : /wp/v2/sites/demo1234.wordpress.com/pages
    Valid route found. Will try to fetch.
    …
    =END PLUGIN=====================================: 5962.415ms
    success source and transform nodes — 6.704 s
    success building schema — 0.369 s
    success createLayouts — 0.030 s
    ⠂ createPages

At this point, `createPages` seems to hang and not produce any output. It doesn't exit, and doesn't produce any errors to the console; it just seems to be waiting for something?

Does anyone know what might be happening here, please?

**Comment by markedup** [comment]
Similar to [@aaronaustin's problem/solution](https://github.com/ericwindmill/gatsby-starter-wordpress/issues/2#issuecomment-386844401), it seemed one post had no tag assigned to it. Adding any arbitrary tag to this one post allowed `createPages` to complete.

This shouldn't break the rendering surely?

**Comment by chmac** [comment]
Were you able to solve this issue?

It looks like you have some fields in the query which do not exist. I guess by now you've probably figured out what the issue was and resolved it, so I'll close this issue. If you're still having problems feel free to reopen and we'll try to help you figure it out.
