### ISSUE TITLE
Having a hard time with Featured Images

### ISSUE THREAD

**Issue by ibjorn** [GatsbyCentral/gatsby-starter-wordpress#53]
I'm really struggling to pull through featured images. I'm hoping I'm just doing something stupid or missing something.

So this is my query in PostList.js:

```javascript
export const pageQuery = graphql`
  fragment PostListFields on wordpress__POST {
    id
    title
    excerpt
    author {
      name
      slug
      avatar_urls {
        wordpress_48
      }
    }
    date(formatString: "MMMM DD, YYYY")
    slug
    featured_media {
      localFile {
        childImageSharp {
          fluid(maxWidth: 1200){
            ...GatsbyImageSharpFluid
        }
      }
    }
  }
}
`
```

And I don't know if I'm wrong, but this is how I get my image:

```javascript
<Img fluid={post.featured_media.localFile.childImageSharp.fluid}  />
```

And I've even tried:

```javascript
<img src={post.featured_media.localFile.childImageSharp.src} />
```

What I end up with is an error that says:

`TypeError: Cannot read property 'localFile' of null`

And if I console.log(posts), I can even see the images:

```javascript
featured_media:
localFile:
childImageSharp:
fluid:
aspectRatio: 1.7777777777777777
base64: "data:image/jpeg;base64,/9j/2wBDABALDA4MCh...etc etc 
sizes: "(max-width: 800px) 100vw, 800px"
src: "/static/cdffa355894ff255a99fe00bb5586590/b17c1/outsource-online-marketing1.jpg"
srcSet: "/static/cdffa355894ff255a99fe00bb5586590/00e5e/outsource-onl
```

I would be so grateful if someone could maybe just point me in the right direction!

**Comment by chmac** [comment]
@ibjorn Your GraphQL query is the issue. You've defined a GraphQL fragment. Check out the docs here for more info:
https://graphql.org/learn/queries/

Bottom line, you need to use this fragment to get the data, check out the http://localhost:8000/___graphql to explore what data is available and how you can get that.

**Comment by ibjorn** [comment]
Hi @chmac So are you saying it's because I am dealing with a fragment that I am unable to get to my media file? Or am I doing something wrong in my modification of the query? I'm still a bit new to GraphQL.

My query is basically copy and pasted from ___graphql, and I can see the image in the results there.

Here's my ___graphql result:

```javascript
{
  "data": {
    "wordpressPost": {
      "id": "3a49e74c-4c28-58ef-b974-xxxx",
      "title": "7 Benefits of Outsourcing Your Online Marketing",
      "excerpt": "xxxxx",
      "author": {
        "name": "xxxx",
        "slug": "xxxx",
        "avatar_urls": {
          "wordpress_48": "https://secure.gravatar.com/avatar/xxxx
        }
      },
      "date": "October 14, 2019",
      "slug": "7-benefits-of-outsourcing-your-online-marketing",
      "featured_media": {
        "localFile": {
          "childImageSharp": {
            "fluid": {
              "originalImg": "/static/cdffa355894ff255a99fe00bb5586590/b17c1/outsource-online-marketing1.jpg",
              "originalName": "outsource-online-marketing1.jpg",
              "presentationWidth": 800,
              "presentationHeight": 450,
              "src": "/static/cdffa355894ff255a99fe00bb5586590/b17c1/outsource-online-marketing1.jpg"
            }
          }
        }
      }
    }
  }
}
```

**Comment by chmac** [comment]
@ibjorn If you copy and paste exactly this into the GraphiQL explorer, it should not return any data:

```graphql
  fragment PostListFields on wordpress__POST {
    id
    title
    excerpt
    author {
      name
      slug
      avatar_urls {
        wordpress_48
      }
    }
    date(formatString: "MMMM DD, YYYY")
    slug
    featured_media {
      localFile {
        childImageSharp {
          fluid(maxWidth: 1200){
            ...GatsbyImageSharpFluid
        }
      }
    }
  }
}
```

The reason is it's just a fragment. It's not a query. You also need a query.

What you posted second looks like the correct data. But somehow you need to tell GraphQL which post you want, so you get the correct post data for that page.

Look at the starter here for example:

https://github.com/GatsbyCentral/gatsby-starter-wordpress/blob/0b89898aea7b872011ee23cd380809ccbc6e7548/src/templates/page.js#L49-L56

It has a `query ...`, the `fragment ...` part is not enough on its own. You can use the fragment inside of a query.

**Comment by ibjorn** [comment]
@chmac Ah oki, I see. So, I can't do that query in a fragment, it needs a separate query. I did not know that. 
Thanks a lot of your help!

**Comment by chmac** [comment]
@ibjorn You can use that fragment inside a query, but you must have a query. Check the GraphQL docs link, they have really nice explanations of what fragments are and so on.

**Comment by ibjorn** [comment]
@chmac Yeah, I'm going to have to brush up a bit on that. Gatsby has been my first introduction to GraphQL, so I'm still finding my way around.
What I was trying to do is add featured images to the blog feed and category list.
