### ISSUE TITLE
CodeSandbox broken

### ISSUE THREAD

**Issue by KarlBaumann** [GatsbyCentral/gatsby-starter-wordpress#71]
Just to let you now, demo in the CodeSandbox does not work anymore.

**Comment by chmac** [comment]
Which demo? I'm not sure what you're referring to when you say "demo in the CodeSandbox"...

**Comment by KarlBaumann** [comment]
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/11026930/110317545-9902ea00-800c-11eb-8465-282e83b5999c.png">

**Comment by chmac** [comment]
@KarlBaumann I believe that's not something we configured, it's provided by gatsby. I'm not sure what the issues are with it, but it's not something we configured as far as I know, and definitely not something we support.

Thanks for reaching out anyway. I'll close this issue now, but if you think I'm missing something, feel free to reopen.
