### ISSUE TITLE
Looking for maintainer...

### ISSUE THREAD

**Issue by zarei-dev** [GatsbyCentral/gatsby-starter-wordpress#87]
_Looking for maintainer: If you're interested in taking over the maintenance of this starter, please reach out in an issue. We're not working with Gatsby any more (it got way too complicated, hello nextjs), and so we're not maintaining this._

Hi. I am ready to maintaine this starter :)

**Comment by chmac** [comment]
Great, thanks for reaching out. What would be your suggestion of how to take over the maintenance, what kind of maintenance would you expect to do, and what's your history with WordPress / Gatsby?
